[wandb]
project = "jax-vs-pt"
name = "none"

[default]
proj_dir = "none"
data_dir = "none"

seed = 0
optim = "SGD"
lr = 0.1
momentum = 0.9
gamma=0.7
weight_decay = 5e-4
lr_scheduler = "StepLR(optimiser, step_size=2, gamma=0.7)"

epochs = 10
batch_size = 128
test_batch_size = 1024

input_size = [1, 28, 28, 1]

[benchmarks]

[models]

[torch]
num_workers = 4
pin_memory = true

[JAX]

[MNIST]
epochs = 30
train_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.1307,], [0.3081,])
    ])"""
test_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.1307,], [0.3081,])
    ])"""

input_size = [1, 28, 28, 1]

[CIFAR10]
epochs = 200
lr_scheduler = "CosineAnnealingLR(optimiser, T_max=200)"
train_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
    ])"""

test_transform = """transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
    ])"""

input_size = [1, 32, 32, 3]

[CITESEER]
epochs = 50
lr = 0.01
sizes = [15, 10]
num_layers = 2
batch_size = 64

in_channels = 3703
hidden_channels = 512
num_classes = 6

[REDDIT]
epochs = 100
lr = 0.01
sizes = [20, 10]
num_layers = 2
batch_size = 1024

in_channels = 602
hidden_channels = 256
num_classes = 41

[PRODUCT]
epochs = 200
size = [25, 10]
num_layers = 2
batch_size = 1024

in_channels = 100
hidden_channels = 256
num_classes = 6

[IMAGENET]
